docs_dir: doc
site_dir: build/html
pages:
    - index.md
    - Reference:
        - "Usage Scenarios": usage.md
site_name: org_heigl-geo
site_description: org_heigl-geo
repo_url: 'https://github.com/heiglandreas/geo'
copyright: 'Copyright (c) <a href="http://andreas.heigl.org/">Andreas Heigl</a>'
